### ISSUE TITLE
can't download

### ISSUE THREAD

**Issue by frolov32** [TheQwertiest/couchpotato.provider.nnm_club#1]
Hello.
Can't download any torrent files.

10-15 22:21:43
ERROR
[                 nnm_club] Failed to parse nnm_club: Traceback (most recent call last):
  File "/Users/macserve/Library/Application Support/CouchPotato/custom_plugins/nnm_club/main.py", line 63, in _searchOnTitle
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by TheQwertiest** [comment]
Hm... Yeah, I think I know what's causing this, will try to roll a fix somewhere around weekend. 
But just in case, can you send a screenshot of the page https://nnm-club.me/forum/tracker.php while you are logged in?

**Comment by frolov32** [comment]
Thanks! 
![screen shot 2015-10-16 at 11 39 47](https://cloud.githubusercontent.com/assets/15147503/10540681/f0dcfce0-7412-11e5-9ca3-08939073859b.png)

**Comment by TheQwertiest** [comment]
Try now, should be fixed.

**Comment by frolov32** [comment]
Sorry, no (

10-16 18:47:06
ERROR
[   couchpotato.core.event] Error in event "provider.search.torrent.movie", that wasn't caught: Traceback (most recent call last):
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/event.py", line 15, in runHandler
  File "/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7/couchpotato/core/media/_base/providers/base.py", line 220, in search
  File "/Users/macserve/Library/Application Support/CouchPotato/custom_plugins/nnm_club/main.py", line 37, in _searchOnTitle
AttributeError: 'str' object has no attribute 'read'
encoding=UTF-8 debug=False args=['--quiet'] app_dir=/Applications/CouchPotato.app/CouchPotato-3.0.1.macosx-10_6-intel/CouchPotato.app/Contents/Resources/lib/python2.7 data_dir=/Users/macserve/Library/Application Support/CouchPotato desktop=<__main__.CouchPotatoApp; proxy of <Swig Object of type 'wxPyApp *' at 0x105763960> > options=Namespace(config_file='/Users/macserve/Library/Application Support/CouchPotato/settings.conf', console_log=False, daemon=False, data_dir=None, debug=False, pid_file='/Users/macserve/Library/Application Support/CouchPotato/couchpotato.pid', quiet=True)

**Comment by TheQwertiest** [comment]
And now it's fixed ;)

**Comment by frolov32** [comment]
Awesome! Now work. Thanks!
Can't understand why when there is an option 'ATV' in Preferred field he is not looking for the releases that mention "ATV"
I am sure they are available on the tracker.
![screen shot 2015-10-23 at 11 28 13](https://cloud.githubusercontent.com/assets/15147503/10688245/a48ae1f4-797b-11e5-94ba-7e7864c02cdf.png)

**Comment by TheQwertiest** [comment]
You are welcome :)
About "filtered" issue: the one who does checking and 'preferring' is CouchPotato - my script just gives it a list of movie titles to check and the script only removes cyrillics and BDRip tag from these titles, so...
