### ISSUE TITLE
Can't find movies

### ISSUE THREAD

**Issue by answer35** [TheQwertiest/couchpotato.provider.nnm_club#3]
Hi,
I am trying to use your plugin but there is a lot of movies whose aren't added to list of download proposal.
I checked on the site manually and could find some result but Couchpotato still doesn't find anything even if I change the name to extend the search.
Here the log that I got for example.
![image](https://cloud.githubusercontent.com/assets/26594746/24189799/abd84fa8-0ee6-11e7-9826-937492bbfd0d.png)
Thank you for your help :)

**Comment by TheQwertiest** [comment]
Please enable debug logging, restart couch potato and make a new log.

**Comment by answer35** [comment]
With debug active, I got this result
![image](https://cloud.githubusercontent.com/assets/26594746/24192785/6c03f0a8-0ef0-11e7-9029-b5dab4546594.png)
I also think about what could be the issue and got an idea. Maybe this is related with the name of the topic whose correct using Russian letters but the torrent name is using the english name or English letters so it probably can't it. Do you think it can be it ?

**Comment by TheQwertiest** [comment]
Yeah, it seems plugin is not proccessing correctly cyrillic name in search query. I'll try to investigate it more thoroughly this week.

PS: Btw as you can see from the log the 1080p release is "(...) unavailable due copyright". Nnmclub restricts access to dl links for some movies, if you have russian IP. And the only way to bypass them is to use proxy.
It looks like this on the web page: ![capture](https://cloud.githubusercontent.com/assets/4470278/24270793/9c517ef0-1027-11e7-89ed-5c0536b16f8f.PNG)

**Comment by TheQwertiest** [comment]
Ok, I've found the issue - I will commit the fix tomorrow.

**Comment by answer35** [comment]
I don't have a russian ip so I don't think that I have this kind of issue.
Good news if you find something to fix that. I hope it will allow me to get what I want easily.

**Comment by TheQwertiest** [comment]
Should be fixed now :)
PS: Can't do anything about copyrighted releases though.
